version: '3'

services: 
  postgres:
    image: 'postgres:10'
    environment: 
      - POSTGRES_PASSWORD=password

  redis:
    image: 'redis:4'
  
  api:
    build: 
      dockerfile: dev.dockerfile
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=password
      - PGPORT=5432
  
  client:
    build: 
      dockerfile: dev.dockerfile
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app

  worker:
    build: 
      dockerfile: dev.dockerfile
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    

  nginx:
    restart: unless-stopped
    build: 
      dockerfile: dev.dockerfile
      context: ./nginx
    ports: 
      - '3000:80'